
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CMD NUMBER SIZE KINDexpression : CMD NUMBER SIZE KIND'
    
_lr_action_items = {'NUMBER':([1,],[3,]),'CMD':([0,],[1,]),'SIZE':([3,],[4,]),'KIND':([4,],[5,]),'$end':([2,5,],[0,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> CMD NUMBER SIZE KIND','expression',4,'p_expression_cmd','pars.py',8),
]
